# Generated by Django 3.1.7 on 2021-03-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicdata',
            fields=[
                ('acousticness', models.FloatField()),
                ('artists', models.TextField()),
                ('danceability', models.FloatField()),
                ('duration_ms', models.FloatField()),
                ('energy', models.FloatField()),
                ('explicit', models.FloatField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('instrumentalness', models.FloatField()),
                ('key', models.FloatField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('mode', models.FloatField()),
                ('name', models.TextField()),
                ('popularity', models.FloatField()),
                ('release_date', models.DateField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('valence', models.FloatField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
