# Generated by Django 3.1.5 on 2021-03-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('artist_name', models.TextField(blank=True, default=None, null=True)),
                ('album_id', models.TextField(primary_key=True, serialize=False)),
                ('album_name', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_name', models.TextField()),
                ('artist_id', models.TextField(primary_key=True, serialize=False)),
                ('artist_popularity', models.FloatField(blank=True, default=None, null=True)),
                ('artist_genres', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.FloatField()),
                ('loudness', models.FloatField()),
                ('mode', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('features_id', models.TextField(primary_key=True, serialize=False)),
                ('duration_ms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.TextField(primary_key=True, serialize=False)),
                ('category_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('artists', models.TextField(blank=True, default=None, null=True)),
                ('track_name', models.TextField(blank=True, default=None, null=True)),
                ('track_id', models.TextField(primary_key=True, serialize=False)),
                ('album_name', models.TextField(blank=True, default=None, null=True)),
                ('explicit', models.BooleanField()),
                ('track_popularity', models.FloatField()),
                ('year', models.IntegerField()),
                ('track_number', models.IntegerField(blank=True, default=None, null=True)),
                ('features_id', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.audiofeatures')),
            ],
        ),
        migrations.DeleteModel(
            name='Musicdata',
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.artist'),
        ),
    ]
