# Generated by Django 3.1.7 on 2021-03-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20210321_1545'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artists'], name='track_artist_index'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['track_name'], name='track_name_index'),
        ),
    ]
