# Generated by Django 3.1.7 on 2021-03-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20210323_1525'),
        ('recommender', '0003_auto_20210325_1533'),
    ]

    operations = [
    ]
