# Generated by Django 3.1.7 on 2021-03-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210326_1815'),
        ('accounts', '0005_user_bio'),
    ]

    operations = [
    ]
